In [ ]:
import numpy as np

In [ ]:
l1=[20,30,40,50]
l2=[60,70,80]
print(l1+l2)

[20, 30, 40, 50, 60, 70, 80]


In [ ]:
arr1=np.array([10,20,30,100])
arr2=np.array([50,60,70,80])
# arr2=np.array([4])
print(arr1+arr2)

[ 60  80 100 180]


**Array Scilicing**

In [ ]:
arr=np.array([[10,20,30,40,50],[60,70,80,90,10]])
print(arr[0:2,0:2]) #give output of first two elements of array first and second
print(arr[0,1:3]) #slice element of first array and give 20,30 as output
print(arr[1,1:3]) #slice element of second array and give 70,80 as output


[[10 20]
 [60 70]]
[20 30]
[70 80]


In [ ]:
arr=np.array([[10,20,30,40,50],[60,70,80,90,10],[20,40,60,80,100]])
print(arr[2,1:3])   #slice element of third array and give 40,60 as output

[40 60]


**Shape Attribute**

In [ ]:
arr=np.array([[10,20,30,40,50],[60,70,80,90,10],[20,40,60,80,100]])
print(np.shape(arr))# 3 row and 5 elements in each row(no of rows and columns)
print(np.size(arr))   #total elements in array
print(np.ndim(arr)) # tow dimention means rows and column
print(arr.dtype)  #check datatype of array
print(type(arr))  #datatype of variable
print(arr.astype(float)) #conversion of datatype

(3, 5)
15
2
int64
<class 'numpy.ndarray'>
[[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90.  10.]
 [ 20.  40.  60.  80. 100.]]


In [ ]:
arr=np.array([[10,20,30,40,50],[60,70,80,90,10],[20,40,60,80,100]])
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)
print(type(arr))

(3, 5)
15
2
int64
<class 'numpy.ndarray'>


**Mathematical operations and function in** **array** **bold text**

In [ ]:
arr1=np.array([10,20,30,40])
arr2=np.array([50,60,70,80])
print(arr1+arr2)
print(np.add(arr1,arr2))

[ 60  80 100 120]
[ 60  80 100 120]


In [ ]:
arr1=np.array([10,20,30,40])
arr2=np.array([50,60,70,80])
print(arr1-arr2)
print(np.subtract(arr1,arr2))

[-40 -40 -40 -40]
[-40 -40 -40 -40]


In [ ]:
arr1=np.array([10,20,30,40])
arr2=np.array([50,60,70,80])
print(arr1*arr2)
print(np.multiply(arr1,arr2))

[ 500 1200 2100 3200]
[ 500 1200 2100 3200]


In [ ]:
arr1=np.array([10,20,30,40])
arr2=np.array([50,60,70,80])
print(arr1/arr2)
print(np.divide(arr1,arr2))

[0.2        0.33333333 0.42857143 0.5       ]
[0.2        0.33333333 0.42857143 0.5       ]


In [ ]:
arr1=np.array([2,4,6,8])
arr2=np.array([2])
print(np.power(arr1,arr2))

[ 4 16 36 64]


In [ ]:
arr1=np.array([4,16,25,36])
print(np.sqrt(arr1))

[2. 4. 5. 6.]
[ 4 16 25 36]


 **combining and spliting array**

In [21]:
import numpy as np
arr1=np.array([10,20,30,40,50,60])
arr2=np.array([60,70,80,90,100,70])
print(np.concatenate([arr1,arr2]))

[ 10  20  30  40  50  60  60  70  80  90 100  70]


In [22]:
print(np.hstack([arr1,arr2]))  #horizontal concatenation

[ 10  20  30  40  50  60  60  70  80  90 100  70]


In [23]:
print(np.vstack([arr1,arr2])) #vertical concatenation

[[ 10  20  30  40  50  60]
 [ 60  70  80  90 100  70]]


**example 2**

In [24]:
arr1=np.array([[30,40],[50,10]])
arr2=np.array([[5,5],[3,3]])
print(np.concatenate([arr1,arr2]))

[[30 40]
 [50 10]
 [ 5  5]
 [ 3  3]]


In [26]:
print(np.hstack([arr1,arr2]))

[[30 40  5  5]
 [50 10  3  3]]


In [27]:
print(np.vstack([arr1,arr2]))

[[30 40]
 [50 10]
 [ 5  5]
 [ 3  3]]


**Spliting Array**

In [28]:
a=np.array([10,30,40,50,60,70,80])
print(np.array_split(a,3))   # 3 show the no of array

[array([10, 30, 40]), array([50, 60]), array([70, 80])]


**Addding and Removing elements from the array**

In [35]:
arr=np.array([20,30,40,50,60,70,80,90,100])
print(np.append(arr,[200,500]))   #append method add element in last index
print(np.insert(arr,2,45))    #insert element at specific position(array,index,value)
print(np.delete(arr,4))

[ 20  30  40  50  60  70  80  90 100 200 500]
[ 20  30  45  40  50  60  70  80  90 100]
[ 20  30  40  50  70  80  90 100]


**Sort ,Filter & Search**

In [36]:
arr=np.array([50,60,30,70,20,10])
print(np.sort(arr))

[10 20 30 50 60 70]


In [38]:
arr=np.array([[50,60,30,70,20,10],[60,65,43,23,55,66]]) # for 2_D array
print(np.sort(arr))

[[10 20 30 50 60 70]
 [23 43 55 60 65 66]]


In [43]:
arr=np.array([50,60,30,70,20,10])
print(np.where(arr==70))
print(np.where(arr % 2==0))

(array([3]),)
(array([0, 1, 2, 3, 4, 5]),)


In [47]:
arr=np.array([50,60,30,70,20,10])
fltr=[True,False,True,False,True,True]
new_arr=arr[fltr]
print(new_arr)

[50 30 20 10]


In [50]:
arr=np.array([50,60,30,70,20,10])       #Filter function(return new arry form existing array)
filter= arr<50
new_arr=arr[filter]
print(new_arr)

[30 20 10]


**Aggregating Function in Array**

In [56]:
arr=np.array([50,60,30,70,20,10])
print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))
print(np.size(arr))
print(np.mean(arr))
print(np.cumsum(arr))   #commulative sum
print(np.cumprod(arr))   #commulative product

240
70
10
6
40.0
[ 50 110 140 210 230 240]
[        50       3000      90000    6300000  126000000 1260000000]


**Statistical Functions In Array**

In [65]:
import statistics as stats
backed_food=[200,300,400,200,30,50,60,60,200,188]
print(np.array(backed_food))
print(np.mean(backed_food))
print(np.median(backed_food))    #median first sort the data and the find the middle value of array
print(stats.mode(backed_food))   # most repeated value is called mode
print(np.std(backed_food))       # standard Deviation(ap ky point means sy kitny dorr hn )
print(np.var(backed_food))       # variance(spread between data points)

[200 300 400 200  30  50  60  60 200 188]
168.8
194.0
200
114.45942512523816
13100.960000000001


**Correlation**

In [66]:
price=[300,400,500,150,200,100]
sales=[10,4,2,10,8,15]
print(np.corrcoef(price,sales))

[[ 1.         -0.91098983]
 [-0.91098983  1.        ]]
